module(...)

-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:d81fbcedc3924d265ef4db187d0b4513$
-- 
-- Usage example:
--			local sheetData = require "ThisFile.lua"
--          local data = sheetData.getSpriteSheetData()
--			local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

function getSpriteSheetData()
    local sheet = {
        frames = {
            {
                name = "assets/ani_die00.png",
                spriteColorRect = { x = 8, y = 6, width = 128, height = 134 },
                textureRect = { x = 128, y = 208, width = 128, height = 134 },
                spriteSourceSize = { width = 140, height = 140 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "assets/ani_idle01.png",
                spriteColorRect = { x = 12, y = 22, width = 116, height = 118 },
                textureRect = { x = 385, y = 68, width = 116, height = 118 },
                spriteSourceSize = { width = 140, height = 140 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "assets/ani_idle02.png",
                spriteColorRect = { x = 10, y = 24, width = 120, height = 116 },
                textureRect = { x = 256, y = 197, width = 120, height = 116 },
                spriteSourceSize = { width = 140, height = 140 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "assets/ani_idle03.png",
                spriteColorRect = { x = 7, y = 24, width = 126, height = 116 },
                textureRect = { x = 128, y = 342, width = 126, height = 116 },
                spriteSourceSize = { width = 140, height = 140 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "assets/ani_jumpdown00.png",
                spriteColorRect = { x = 0, y = 34, width = 140, height = 106 },
                textureRect = { x = 256, y = 313, width = 140, height = 106 },
                spriteSourceSize = { width = 140, height = 140 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "assets/ani_land00.png",
                spriteColorRect = { x = 5, y = 38, width = 128, height = 102 },
                textureRect = { x = 376, y = 197, width = 128, height = 102 },
                spriteSourceSize = { width = 140, height = 140 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "assets/blur1.png",
                spriteColorRect = { x = 4, y = 0, width = 128, height = 138 },
                textureRect = { x = 0, y = 348, width = 128, height = 138 },
                spriteSourceSize = { width = 140, height = 140 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "assets/blur2.png",
                spriteColorRect = { x = 4, y = 0, width = 128, height = 140 },
                textureRect = { x = 128, y = 68, width = 128, height = 140 },
                spriteSourceSize = { width = 140, height = 140 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "assets/blur3.png",
                spriteColorRect = { x = 4, y = 0, width = 128, height = 140 },
                textureRect = { x = 0, y = 208, width = 128, height = 140 },
                spriteSourceSize = { width = 140, height = 140 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "assets/blur4.png",
                spriteColorRect = { x = 4, y = 0, width = 128, height = 140 },
                textureRect = { x = 0, y = 68, width = 128, height = 140 },
                spriteSourceSize = { width = 140, height = 140 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "assets/btn_zoom.png",
                spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
                textureRect = { x = 418, y = 463, width = 32, height = 32 },
                spriteSourceSize = { width = 32, height = 32 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "assets/complete.png",
                spriteColorRect = { x = 8, y = 13, width = 424, height = 68 },
                textureRect = { x = 0, y = 0, width = 424, height = 68 },
                spriteSourceSize = { width = 440, height = 84 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "assets/obj_box01.png",
                spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
                textureRect = { x = 354, y = 419, width = 64, height = 64 },
                spriteSourceSize = { width = 64, height = 64 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "assets/obj_box02.png",
                spriteColorRect = { x = 0, y = 0, width = 129, height = 129 },
                textureRect = { x = 256, y = 68, width = 129, height = 129 },
                spriteSourceSize = { width = 129, height = 129 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "assets/obj_box03.png",
                spriteColorRect = { x = 0, y = 0, width = 64, height = 32 },
                textureRect = { x = 418, y = 393, width = 64, height = 32 },
                spriteSourceSize = { width = 64, height = 32 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "assets/obj_box04.png",
                spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
                textureRect = { x = 424, y = 0, width = 64, height = 64 },
                spriteSourceSize = { width = 64, height = 64 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "assets/obj_box05.png",
                spriteColorRect = { x = 0, y = 0, width = 96, height = 32 },
                textureRect = { x = 128, y = 458, width = 96, height = 32 },
                spriteSourceSize = { width = 96, height = 32 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "assets/obj_enemy.png",
                spriteColorRect = { x = 21, y = 46, width = 100, height = 94 },
                textureRect = { x = 396, y = 299, width = 100, height = 94 },
                spriteSourceSize = { width = 140, height = 140 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "assets/obj_enemy2.png",
                spriteColorRect = { x = 0, y = 2, width = 100, height = 93 },
                textureRect = { x = 254, y = 419, width = 100, height = 93 },
                spriteSourceSize = { width = 102, height = 95 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "assets/obj_ico_enemies.png",
                spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
                textureRect = { x = 454, y = 425, width = 32, height = 32 },
                spriteSourceSize = { width = 32, height = 32 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "assets/obj_ko_star00.png",
                spriteColorRect = { x = 12, y = 12, width = 16, height = 16 },
                textureRect = { x = 496, y = 299, width = 16, height = 16 },
                spriteSourceSize = { width = 40, height = 40 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "assets/obj_ko_star01.png",
                spriteColorRect = { x = 6, y = 6, width = 28, height = 28 },
                textureRect = { x = 224, y = 458, width = 28, height = 28 },
                spriteSourceSize = { width = 40, height = 40 },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "assets/obj_ko_star02.png",
                spriteColorRect = { x = 1, y = 1, width = 36, height = 38 },
                textureRect = { x = 418, y = 425, width = 36, height = 38 },
                spriteSourceSize = { width = 40, height = 40 },
                spriteTrimmed = true,
                textureRotated = false
            },
        }
    }
    return sheet
end

